apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  BACKGROUND_IMAGE_URL: https://clo835-final-group9-background-bucket.s3.us-east-1.amazonaws.com/background2.jpg
  DEVELOPER_NAMES: Hongwei Zhao and Alex Zhou