apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: employees
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: clo835-group9  # Place this under template.spec
      containers:
      - name: webapp
        image: 444868690040.dkr.ecr.us-east-1.amazonaws.com/clo835-final-webapp-repo:v0.4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: BACKGROUND_IMAGE_URL
        - name: DEVELOPER_NAMES
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: DEVELOPER_NAMES
        - name: GET_HOSTS_FROM
          value: dns
        - name: DBPORT
          value: "3306"  # Port to MySQL DB
        - name: DBHOST
          value: "mysql"  # Name of MySQL service
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DBUSER 
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DBPWD   # Root password
        - name: APP_COLOR
          value: "blue"
        ports:
        - containerPort: 81