apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql  # unique name of deployment in its namespace
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql
        image: 444868690040.dkr.ecr.us-east-1.amazonaws.com/clo835-final-mysql-repo:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        #args:
          #- --bind_ip
          #- 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306