apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 81          # The external port exposed by the LoadBalancer
      targetPort: 81    # The port inside the container
  selector:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend