apiVersion: v1
kind: Secret
metadata:
  name: secret-credentials
type: Opaque
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: cHc=
  AWS_ACCESS_KEY_ID: QVNJQVNKMkZQWVJVRkZLWU1GWTQ=
  AWS_SECRET_ACCESS_KEY: eWVHRm0xcFUxdkRDak5XY1F1S3gvMDB2ejhYQlYrUkN1a3l0eXNMcg==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVJdi8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lBMTVsRmVZbFhDUUpkcWNIZWdKVFRJRnB4OERIZGhIaGk4RzFid3kyZ3pBQWlFQXBrWE1ScGIzaFNCQmQ4WDFZbDhsVk1udS9lUTZuNjVYMndJaU1OaGlKS3NxclFJSVJCQUJHZ3d4TlRnMU1qSTJOVFU0TkRnaURGZk5MQkc1a3cvL1BuLzhnaXFLQWdubUtWL0FHbFZKcDhDN3dtVVdTL3YwMCt3WDVkOUd0M2pHQ2wwU1hST1E3ZWlvRVFEMWU4MElSdUw4WVhzMzFJSDY4RG5PUlo5bEYxMjJCRmZDUEw4RVZMamNpY0E3QW5BQ2ptaFhBZ0QwM2trdmdhTVFFaXoyeFVaMHpwaUhxdFUzRlRFVUFkSjJLNGZRVmdhNW5EQ29ud0J3WkhIUjJTT2NWUFNmY1FUUXFBMHJ3cFdzbTVETGlBYkhlb3RhSElaOWU0MUw4TVJiS04veUJWL3ovUkF6bFRqUkVUOWcwaTgzRG1GNEpMNWdhZUVKa3h1aVVIbHpFZ2UyUjhRVHVWZWhYamljNlVOM05WdnBSQjBBTFpNbFlSdThOL0FiVS9NeFdwSElBYmg2b1JIQWNpNk9SYVpyZjRDaWpQWElkbWtwRXJPajhpNVdmZFJ0ZzluZEk5cENPL25oY3JKWTVLbHRNSzdkMExvR09wMEJ6NWYxQzZTRnRpSDBrbUhkdFR6L1d2Sno3K3U2ck5LTWFvalRlYmlleU1NbTYrZGVacXJCVnhKdkNiSUZwNW9UbStpdUFwR01tdTlQbGhHb1JndytPdEhmdkhmejZySFMrQ0M1UkllMk50ZEUwYnpZOUM2cUo4dzRoN2l4d0d2eEhhdTNVTEJkMDN2MU1DbFVOTVJEWVdPeFBLTk9tVXMvNlNOSEZHNENDWnhQc2RxSDhBWE12T3J0MFdudy9FeVQwQnV1TFVsSmxTUUpMZU5LTlE9PQ==
