name: Deploy to ECR
# Updated ECR Repo CLO835 Final Project 12/04/2024
on: 
  push:
    branches: [ master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

    # Check out code
    - name: Check out code
      uses: actions/checkout@v2

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    # Build, tag, and push the Web Application image
    - name: Build, tag, and push Web Application image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_WEBAPP: clo835-final-webapp-repo
        IMAGE_TAG: latest
      run: |
        ls -ltra
        # Build the Docker image for the Web Application
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_WEBAPP:$IMAGE_TAG -f Dockerfile .
        # Push the Web Application image to Amazon ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_WEBAPP:$IMAGE_TAG

    # Build, tag, and push the MySQL Database image
    - name: Build, tag, and push MySQL Database image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_MYSQL: clo835-final-mysql-repo
        IMAGE_TAG: latest
      run: |
        ls -ltra
        # Build the Docker image for MySQL Database
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_MYSQL:$IMAGE_TAG -f Dockerfile_mysql .
        # Push the MySQL Database image to Amazon ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_MYSQL:$IMAGE_TAG

    # Upload background image to S3 bucket
    - name: Upload Background Image to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        # Install AWS CLI
        sudo apt-get update && sudo apt-get install -y awscli
        # Upload the image to the S3 bucket
        aws s3 cp background.jpg s3://clo835-final-group9-background-bucket/